spring:
  datasource:
    url: jdbc:mysql://mysql-ec69418-sistema-hotel.i.aivencloud.com:22116/defaultdb?sslMode=REQUIRED
    username: avnadmin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: sG9@fP!3kZrL#uN7wXqVtY$bD2eM0cA1
