spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: programador16
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: sG9@fP!3kZrL#uN7wXqVtY$bD2eM0cA1

